title: Masque Works
theme: just-the-docs
logo: "/images/MasqueLogo_1080p.png"
favicon_ico: "/images/masqueicon.ico"

url: https://masqueworks.com

color_scheme: dark

footer_content: "Copyright &copy; 2025 Masque Works, LLC."
