title: Masque Works
theme: just-the-docs
logo: "/images/MasqueIcon.png"
favicon_ico: "/images/masqueicon.ico"

url: https://masqueworks.com

collections:
  docs:
    output: true

Navigation:
- title: Forums
 url: https://github.com/masqueworks/masque-app-deploy/discussions
    
color_scheme: dark

footer_content: "Copyright &copy; 2025 Masque Works, LLC."
